### ISSUE TITLE
Dependencies defeat the purpose of using rust over bash

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/safe-hash-rs#9]
This list of dependencies increases the attack surface of this tool. The bash tool is only dependent on foundry, but it could be easily repurposed to remove that dependency. Adding these dependencies here isn't really an improvement. We would need to make this without some of these dependencies. 

```toml
[workspace.dependencies]
semver = "1.0"
alloy = { version = "0.11.1", features = ["essentials"] }
serde = { version = "1", features = ["derive"] }
clap = { version = "4.5.31", features = ["derive"] }
reqwest = { version = "0.12.2", default-features = false, features = ["blocking", "json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
color-print = "0.3"
cli-table = "0.4"
sty = "0.3"
```
